server:
  port: 8122
url:
  userRoot: http://localhost:8123
  deactivateUser: /users/deactivate/
  getUsers: /users/search/findAllByDeactivatedFalse
  saveUser: /users
logging:
  level:
    com:
      example: DEBUG